### ISSUE TITLE
--file-chooser 不存在

### ISSUE THREAD

**Issue by zhang-yunqi** [theniceboy/joshuto.nvim#2]
# --file-chooser 不存在
最新版的joshuto取消了--file-chooser 选项
## 解决方案如下
在./lua/joshuto.lua中找到这么一行：
```lua
local cmd = string.format('joshuto --file-chooser --output-file %s %s', output_path, path)
```
改为

```lua
local cmd = string.format('joshuto --file-chooser --output-file %s', path)
```

**Comment by theniceboy** [comment]
诶？我用的就是最新版。你确定你用的不是旧版的joshuto吗？

**Comment by namespacebilibili** [comment]
> # --file-chooser 不存在
> 最新版的joshuto取消了--file-chooser 选项
> 
> ## 解决方案如下
> 在./lua/joshuto.lua中找到这么一行：
> 
> ```lua
> local cmd = string.format('joshuto --file-chooser --output-file %s %s', output_path, path)
> ```
> 
> 改为
> 
> ```lua
> local cmd = string.format('joshuto --file-chooser --output-file %s', path)
> ```

还是不行，显示没有--file-chooser

**Comment by zhuhu00** [comment]
一样的问题，
```
error: Found argument '--file-chooser' which wasn't expected, or isn't valid in this context

USAGE:
    joshuto [OPTIONS]

For more information try --help

[Process exited 1]

```

**Comment by theniceboy** [comment]
你的joshuto版本是什么？

**Comment by zhuhu00** [comment]
joshuto-0.9.4

**Comment by theniceboy** [comment]
@zhuhu00 你能运行一下`joshuto -h`吗？这是我的运行结果：
```
$ joshuto -h
joshuto 0.9.4

USAGE:
    joshuto [FLAGS] [OPTIONS] [ARGUMENTS]...

FLAGS:
        --change-directory
        --file-chooser
    -h, --help                Prints help information
    -v, --version

OPTIONS:
        --output-file <output-file>

ARGS:
    <ARGUMENTS>...
```

能看到我的版本是0.9.4，里面有`--file-chooser`

**Comment by zhuhu00** [comment]
@theniceboy 我的运行了没有哎，
➜  ~ joshuto -h
joshuto 0.9.4

USAGE:
    joshuto [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -v, --version

OPTIONS:
        --output-file <output-file>
        --path <path>

我是今早下的，电脑是mac m1 pro. 使用port下载的。`sudo port install joshuto`，难道说是安装方式不对？

**Comment by theniceboy** [comment]
离谱😂😂建议给作者开个issue  下到盗版可还行😂

我是compile的源码，你可以试试

**Comment by zhuhu00** [comment]
从源码编译后的能够正常用了。。还必须编译最新的，之前release的0.9.4也没有包含--file-chooser。

**Comment by namespacebilibili** [comment]
build失败可以看这个https://github.com/kamiyaa/joshuto/issues/318

**Comment by theniceboy** [comment]
joshuto更新了，这个flag应该已经在最新的release了
